export const categoryEnum = ['casual', 'formal', 'sportswear', 'sleepwear', 'outerwear', 'workoutwear'] as const;
export type CategoryTypes = typeof categoryEnum[number]

export const CATEGORY: ReadonlyArray<{ image_url: string; category_name: CategoryTypes }> = [
  {
    image_url: "/All-Category/Top-Wear/2NA22S0C3-K11@12.jpg",
    category_name: "casual",
  },
  {
    image_url: "/All-Category/Top-Wear/2NA22S0C9-C11@12.jpg",
    category_name: "formal",
  },
  {
    image_url: "/All-Category/Top-Wear/2NA22S0C9-K11@12.jpg",
    category_name: "outerwear",
  },
  {
    image_url: "/All-Category/Top-Wear/2NA22S0C9-N11@12.jpg",
    category_name: "sleepwear",
  },
  {
    image_url: "/All-Category/Top-Wear/2NA22S0CA-K11@10.jpg",
    category_name: "sportswear",
  },
  {
    image_url: "/All-Category/Top-Wear/2NA22S0CA-Q11@12.jpg",
    category_name: "workoutwear",
  },
];

export const PRODUCT_CARD_RESPONSE = {
  status: 200,
  message: "Cart fetched successfully.",
  data: {
    cart: {
      items: [
        {
          product: {
            _id: "1",
            name: "Product 1",
            slug: "product-1",
            category: "bottom-wear",
            price: 6031.51,
            image: "/Main-Product-Card/1.jpg",
          },
          quantity: 2,
          itemTotal: 12063.02,
        },
        {
          product: {
            _id: "2",
            name: "Product 2",
            slug: "product-2",
            category: "bottom-wear",
            price: 6053.8,
            image: "/Main-Product-Card/2.jpeg",
          },
          quantity: 5,
          itemTotal: 30269.0,
        },
        {
          product: {
            _id: "3",
            name: "Product 3",
            slug: "product-3",
            category: "bottom-wear",
            price: 7815.41,
            image: "/Main-Product-Card/3.jpg",
          },
          quantity: 6,
          itemTotal: 46892.46,
        },
        {
          product: {
            _id: "4",
            name: "Product 4",
            slug: "product-4",
            category: "bottom-wear",
            price: 2624.49,
            image: "/Main-Product-Card/4.jpg",
          },
          quantity: 3,
          itemTotal: 7873.47,
        },
        {
          product: {
            _id: "5",
            name: "Product 5",
            slug: "product-5",
            category: "bottom-wear",
            price: 1459.7,
            image: "/Main-Product-Card/5.webp",
          },
          quantity: 5,
          itemTotal: 7298.5,
        },
        {
          product: {
            _id: "6",
            name: "Product 6",
            slug: "product-6",
            category: "bottom-wear",
            price: 1139.4,
            image: "/Main-Product-Card/6.jpg",
          },
          quantity: 1,
          itemTotal: 1139.4,
        },
        {
          product: {
            _id: "7",
            name: "Product 7",
            slug: "product-7",
            category: "bottom-wear",
            price: 2367.38,
            image: "/Main-Product-Card/7.jpg",
          },
          quantity: 5,
          itemTotal: 11836.9,
        },
        {
          product: {
            _id: "8",
            name: "Product 8",
            slug: "product-8",
            category: "bottom-wear",
            price: 6121.77,
            image: "/Main-Product-Card/8.jpg",
          },
          quantity: 1,
          itemTotal: 6121.77,
        },
        {
          product: {
            _id: "9",
            name: "Product 9",
            slug: "product-9",
            category: "bottom-wear",
            price: 1919.88,
            image: "/Main-Product-Card/9.jpg",
          },
          quantity: 5,
          itemTotal: 9599.4,
        },
        {
          product: {
            _id: "10",
            name: "Product 10",
            slug: "product-10",
            category: "bottom-wear",
            price: 5340.12,
            image: "/Main-Product-Card/10.jpg",
          },
          quantity: 5,
          itemTotal: 26700.6,
        },
        {
          product: {
            _id: "11",
            name: "Product 11",
            slug: "product-11",
            category: "bottom-wear",
            price: 5553.82,
            image: "/Main-Product-Card/11.jpg",
          },
          quantity: 5,
          itemTotal: 27769.1,
        },
        {
          product: {
            _id: "12",
            name: "Product 12",
            slug: "product-12",
            category: "bottom-wear",
            price: 9163.66,
            image: "/Main-Product-Card/12.webp",
          },
          quantity: 3,
          itemTotal: 27490.98,
        },
        {
          product: {
            _id: "13",
            name: "Product 13",
            slug: "product-13",
            category: "bottom-wear",
            price: 6088.11,
            image: "/Main-Product-Card/13.jpg",
          },
          quantity: 2,
          itemTotal: 12176.22,
        },
        {
          product: {
            _id: "14",
            name: "Product 14",
            slug: "product-14",
            category: "bottom-wear",
            price: 815.47,
            image: "/Main-Product-Card/14.jpg",
          },
          quantity: 4,
          itemTotal: 3261.88,
        },
        {
          product: {
            _id: "15",
            name: "Product 15",
            slug: "product-15",
            category: "bottom-wear",
            price: 1491.73,
            image: "/Main-Product-Card/15.jpg",
          },
          quantity: 6,
          itemTotal: 8950.38,
        },
        {
          product: {
            _id: "16",
            name: "Product 16",
            slug: "product-16",
            category: "bottom-wear",
            price: 2874.83,
            image: "/Main-Product-Card/16.jpg",
          },
          quantity: 4,
          itemTotal: 11499.32,
        },
        {
          product: {
            _id: "17",
            name: "Product 17",
            slug: "product-17",
            category: "bottom-wear",
            price: 8374.84,
            image: "/Main-Product-Card/17.jpg",
          },
          quantity: 3,
          itemTotal: 25124.52,
        },
        {
          product: {
            _id: "18",
            name: "Product 18",
            slug: "product-18",
            category: "bottom-wear",
            price: 4553.14,
            image: "/Main-Product-Card/18.jpg",
          },
          quantity: 2,
          itemTotal: 9106.28,
        },
        {
          product: {
            _id: "19",
            name: "Product 19",
            slug: "product-19",
            category: "bottom-wear",
            price: 7419.06,
            image: "/Main-Product-Card/19.jpg",
          },
          quantity: 6,
          itemTotal: 44514.36,
        },
        {
          product: {
            _id: "20",
            name: "Product 20",
            slug: "product-20",
            category: "bottom-wear",
            price: 4894.08,
            image: "/Main-Product-Card/20.jpg",
          },
          quantity: 6,
          itemTotal: 29364.48,
        },
        {
          product: {
            _id: "21",
            name: "Product 21",
            slug: "product-21",
            category: "bottom-wear",
            price: 7591.37,
            image: "/Main-Product-Card/21.jpg",
          },
          quantity: 5,
          itemTotal: 37956.85,
        },
        {
          product: {
            _id: "22",
            name: "Product 22",
            slug: "product-22",
            category: "bottom-wear",
            price: 4600.43,
            image: "/Main-Product-Card/22.jpg",
          },
          quantity: 4,
          itemTotal: 18401.72,
        },
        {
          product: {
            _id: "23",
            name: "Product 23",
            slug: "product-23",
            category: "bottom-wear",
            price: 1808.07,
            image: "/Main-Product-Card/23.jpg",
          },
          quantity: 2,
          itemTotal: 3616.14,
        },
        {
          product: {
            _id: "24",
            name: "Product 24",
            slug: "product-24",
            category: "bottom-wear",
            price: 606.1,
            image: "/Main-Product-Card/24.jpg",
          },
          quantity: 6,
          itemTotal: 3636.6,
        },
        {
          product: {
            _id: "25",
            name: "Product 25",
            slug: "product-25",
            category: "bottom-wear",
            price: 6489.05,
            image: "/Main-Product-Card/25.jpg",
          },
          quantity: 6,
          itemTotal: 38934.3,
        },
        {
          product: {
            _id: "26",
            name: "Product 26",
            slug: "product-26",
            category: "bottom-wear",
            price: 9022.62,
            image: "/Main-Product-Card/26.jpg",
          },
          quantity: 1,
          itemTotal: 9022.62,
        },
        {
          product: {
            _id: "27",
            name: "Product 27",
            slug: "product-27",
            category: "bottom-wear",
            price: 6795.38,
            image: "/Main-Product-Card/27.jpeg",
          },
          quantity: 1,
          itemTotal: 6795.38,
        },
        {
          product: {
            _id: "28",
            name: "Product 28",
            slug: "product-28",
            category: "bottom-wear",
            price: 6448.91,
            image: "/Main-Product-Card/28.webp",
          },
          quantity: 3,
          itemTotal: 19346.73,
        },
        {
          product: {
            _id: "29",
            name: "Product 29",
            slug: "product-29",
            category: "bottom-wear",
            price: 6572.66,
            image: "/Main-Product-Card/29.jpg",
          },
          quantity: 3,
          itemTotal: 19717.98,
        },
        {
          product: {
            _id: "30",
            name: "Product 30",
            slug: "product-30",
            category: "bottom-wear",
            price: 6908.69,
            image: "/Main-Product-Card/30.jpg",
          },
          quantity: 5,
          itemTotal: 34543.45,
        },
        {
          product: {
            _id: "31",
            name: "Product 31",
            slug: "product-31",
            category: "bottom-wear",
            price: 8722.03,
            image: "/Main-Product-Card/31.jpg",
          },
          quantity: 3,
          itemTotal: 26166.09,
        },
        {
          product: {
            _id: "32",
            name: "Product 32",
            slug: "product-32",
            category: "bottom-wear",
            price: 3271.04,
            image: "/Main-Product-Card/32.jpeg",
          },
          quantity: 3,
          itemTotal: 9813.12,
        },
        {
          product: {
            _id: "33",
            name: "Product 33",
            slug: "product-33",
            category: "bottom-wear",
            price: 1278.01,
            image: "/Main-Product-Card/33.jpg",
          },
          quantity: 2,
          itemTotal: 2556.02,
        },
        {
          product: {
            _id: "34",
            name: "Product 34",
            slug: "product-34",
            category: "bottom-wear",
            price: 8324.87,
            image: "/Main-Product-Card/34.jpeg",
          },
          quantity: 2,
          itemTotal: 16649.74,
        },
        {
          product: {
            _id: "35",
            name: "Product 35",
            slug: "product-35",
            category: "bottom-wear",
            price: 6727.72,
            image: "/Main-Product-Card/35.jpg",
          },
          quantity: 2,
          itemTotal: 13455.44,
        },
        {
          product: {
            _id: "36",
            name: "Product 36",
            slug: "product-36",
            category: "bottom-wear",
            price: 1807.16,
            image: "/Main-Product-Card/36.jpeg",
          },
          quantity: 6,
          itemTotal: 10842.96,
        },
        {
          product: {
            _id: "37",
            name: "Product 37",
            slug: "product-37",
            category: "bottom-wear",
            price: 543.77,
            image: "/Main-Product-Card/37.jpg",
          },
          quantity: 4,
          itemTotal: 2175.08,
        },
        {
          product: {
            _id: "38",
            name: "Product 38",
            slug: "product-38",
            category: "bottom-wear",
            price: 5912.66,
            image: "/Main-Product-Card/38.jpg",
          },
          quantity: 5,
          itemTotal: 29563.3,
        },
        {
          product: {
            _id: "39",
            name: "Product 39",
            slug: "product-39",
            category: "bottom-wear",
            price: 675.55,
            image: "/Main-Product-Card/39.jpg",
          },
          quantity: 5,
          itemTotal: 3377.75,
        },
        {
          product: {
            _id: "40",
            name: "Product 40",
            slug: "product-40",
            category: "bottom-wear",
            price: 6791.54,
            image: "/Main-Product-Card/40.jpg",
          },
          quantity: 6,
          itemTotal: 40749.24,
        },
        {
          product: {
            _id: "41",
            name: "Product 41",
            slug: "product-41",
            category: "bottom-wear",
            price: 8636.4,
            image: "/Main-Product-Card/41.jpg",
          },
          quantity: 4,
          itemTotal: 34545.6,
        },
        {
          product: {
            _id: "42",
            name: "Product 42",
            slug: "product-42",
            category: "bottom-wear",
            price: 2160.31,
            image: "/Main-Product-Card/42.jpg",
          },
          quantity: 1,
          itemTotal: 2160.31,
        },
        {
          product: {
            _id: "43",
            name: "Product 43",
            slug: "product-43",
            category: "bottom-wear",
            price: 3841.34,
            image: "/Main-Product-Card/43.jpg",
          },
          quantity: 2,
          itemTotal: 7682.68,
        },
        {
          product: {
            _id: "44",
            name: "Product 44",
            slug: "product-44",
            category: "bottom-wear",
            price: 3492.84,
            image: "/Main-Product-Card/44.jpg",
          },
          quantity: 5,
          itemTotal: 17464.2,
        },
        {
          product: {
            _id: "45",
            name: "Product 45",
            slug: "product-45",
            category: "bottom-wear",
            price: 2672.1,
            image: "/Main-Product-Card/45.jpg",
          },
          quantity: 3,
          itemTotal: 8016.3,
        },
        {
          product: {
            _id: "46",
            name: "Product 46",
            slug: "product-46",
            category: "bottom-wear",
            price: 806.53,
            image: "/Main-Product-Card/46.jpg",
          },
          quantity: 6,
          itemTotal: 4839.18,
        },
        {
          product: {
            _id: "47",
            name: "Product 47",
            slug: "product-47",
            category: "bottom-wear",
            price: 1667.47,
            image: "/Main-Product-Card/47.jpg",
          },
          quantity: 5,
          itemTotal: 8337.35,
        },
        {
          product: {
            _id: "48",
            name: "Product 48",
            slug: "product-48",
            category: "bottom-wear",
            price: 9753.58,
            image: "/Main-Product-Card/48.jpg",
          },
          quantity: 5,
          itemTotal: 48767.9,
        },
        {
          product: {
            _id: "49",
            name: "Product 49",
            slug: "product-49",
            category: "bottom-wear",
            price: 8662.54,
            image: "/Main-Product-Card/49.jpg",
          },
          quantity: 6,
          itemTotal: 51975.24,
        },
        {
          product: {
            _id: "50",
            name: "Product 50",
            slug: "product-50",
            category: "bottom-wear",
            price: 883.71,
            image: "/Main-Product-Card/50.jpg",
          },
          quantity: 1,
          itemTotal: 883.71,
        },
      ],
      totalPrice: 891045.02,
      totalQuantity: 191,
    },
  },
};
