import type { CartType, ProductDetailsType, ProductType } from "@/types/products";

export const categoryEnum = ['casual', 'formal', 'sportswear', 'sleepwear', 'outerwear', 'workoutwear'] as const;
export type CategoryTypes = typeof categoryEnum[number]


export const PRODUCT_LIST: ProductType[] = [
  {
    _id: "1",
    name: "Classic White Shirt",
    slug: "classic-white-shirt",
    brand: "Zara",
    price: 1999,
    category: "Shirts",
    dressType: "Casual",
    images: ["/Main-Product-Card/1.jpg"],
    createdAt: "2025-09-30T08:00:00.000Z",
    isFav: false,
    sold: 320,
    viewCount: 1450,
    rating: 4.5,
    description:
      "This classic white shirt from Zara is designed for effortless everyday styling and long-lasting comfort. Crafted using breathable fabric, it offers a clean silhouette suitable for both casual and semi-formal occasions. The soft texture ensures all-day wearability, while the tailored fit enhances your overall look. Pair it with jeans, chinos, or layered outfits for a timeless wardrobe essential that never goes out of style.",
  },
  {
    _id: "2",
    name: "Slim Fit Jeans",
    slug: "slim-fit-jeans",
    brand: "Levi's",
    price: 3499,
    category: "Pants",
    dressType: "Denim",
    images: ["/Main-Product-Card/2.jpeg"],
    createdAt: "2025-09-29T12:00:00.000Z",
    isFav: true,
    sold: 780,
    viewCount: 2850,
    rating: 4.7,
    description:
      "Levi’s slim fit jeans are crafted for a modern silhouette with superior comfort and durability. Made from high-quality denim, they provide excellent stretch while retaining shape throughout the day. These jeans are perfect for casual outings, workwear styling, or weekend wear. Designed to complement sneakers, boots, or formal shoes, they deliver a versatile look that adapts easily to multiple fashion needs.",
  },
  {
    _id: "3",
    name: "Black Leather Jacket",
    slug: "black-leather-jacket",
    brand: "H&M",
    price: 5999,
    category: "Jackets",
    dressType: "Leather",
    images: ["/Main-Product-Card/3.jpg"],
    createdAt: "2025-09-28T10:30:00.000Z",
    isFav: false,
    sold: 150,
    viewCount: 1200,
    rating: 4.3,
    description:
      "This black leather jacket from H&M delivers a bold and confident style statement. Designed with a sleek finish and comfortable inner lining, it offers warmth and durability without compromising on style. Ideal for layering during cooler seasons, it pairs effortlessly with jeans or boots. The structured design and premium look make it suitable for casual evenings, travel, and urban fashion styling.",
  },
  {
    _id: "4",
    name: "Summer Floral Dress",
    slug: "summer-floral-dress",
    brand: "Forever 21",
    price: 2499,
    category: "Dresses",
    dressType: "Casual",
    images: ["/Main-Product-Card/4.jpg"],
    createdAt: "2025-09-27T16:45:00.000Z",
    isFav: true,
    sold: 600,
    viewCount: 3000,
    rating: 4.8,
    description:
      "The summer floral dress from Forever 21 features a vibrant design that captures fresh seasonal style. Made from lightweight and breathable fabric, it ensures comfort even on warm days. The flattering fit and flowing silhouette enhance movement and elegance. Perfect for casual outings, vacations, or daytime events, this dress adds a cheerful and stylish touch to any wardrobe.",
  },
  {
    _id: "5",
    name: "Running Sneakers",
    slug: "running-sneakers",
    brand: "Nike",
    price: 4999,
    category: "Shoes",
    dressType: "Sportswear",
    images: ["/Main-Product-Card/5.webp"],
    createdAt: "2025-09-26T09:15:00.000Z",
    isFav: false,
    sold: 850,
    viewCount: 5200,
    rating: 4.6,
    description:
      "Nike running sneakers are engineered for performance, comfort, and everyday athletic use. Featuring cushioned soles and breathable materials, they provide excellent support during workouts and long walks. The lightweight construction reduces foot fatigue while ensuring stability and grip. Designed for runners and fitness enthusiasts, these sneakers blend sporty aesthetics with functionality for active lifestyles.",
  },
  {
    _id: "6",
    name: "Woolen Winter Coat",
    slug: "woolen-winter-coat",
    brand: "Mango",
    price: 7999,
    category: "Coats",
    dressType: "Winter",
    images: ["/Main-Product-Card/6.jpg"],
    createdAt: "2025-09-25T13:20:00.000Z",
    isFav: false,
    sold: 220,
    viewCount: 1750,
    rating: 4.4,
    description:
      "This woolen winter coat from Mango offers superior warmth with a refined and elegant look. Crafted from high-quality wool fabric, it provides insulation during colder months while maintaining breathability. The structured design complements both casual and formal outfits. Ideal for winter travel and daily wear, this coat combines comfort, durability, and timeless seasonal style.",
  },
  {
    _id: "7",
    name: "Formal Blazer",
    slug: "formal-blazer",
    brand: "Raymond",
    price: 5499,
    category: "Suits",
    dressType: "Formal",
    images: ["/Main-Product-Card/7.jpg"],
    createdAt: "2025-09-24T18:30:00.000Z",
    isFav: true,
    sold: 410,
    viewCount: 2100,
    rating: 4.5,
    description:
      "Raymond’s formal blazer is tailored for a sharp and professional appearance. Made with premium fabric, it offers a structured fit while remaining comfortable for long hours. Suitable for office wear, meetings, and formal events, this blazer enhances confidence and sophistication. Its versatile design pairs well with trousers or formal shirts, making it an essential piece for business wardrobes.",
  },
  {
    _id: "8",
    name: "Graphic T-Shirt",
    slug: "graphic-tshirt",
    brand: "Uniqlo",
    price: 1499,
    category: "T-Shirts",
    dressType: "Casual",
    images: ["/Main-Product-Card/8.jpg"],
    createdAt: "2025-09-23T11:10:00.000Z",
    isFav: false,
    sold: 940,
    viewCount: 4300,
    rating: 4.7,
    description:
      "This graphic T-shirt from Uniqlo is designed for casual comfort and modern street style. Crafted from soft cotton fabric, it ensures breathability and all-day ease. The bold graphic print adds personality to everyday outfits, making it perfect for relaxed outings. Easy to pair with jeans or shorts, this T-shirt offers a trendy yet comfortable wardrobe staple.",
  },
  {
    _id: "9",
    name: "Casual Blue Denim Shirt",
    slug: "casual-blue-denim-shirt",
    brand: "Wrangler",
    price: 2599,
    category: "Shirts",
    dressType: "Casual",
    images: ["/Main-Product-Card/9.jpg"],
    createdAt: "2025-09-22T09:00:00.000Z",
    isFav: false,
    sold: 410,
    viewCount: 1800,
    rating: 4.4,
    description:
      "Wrangler’s casual blue denim shirt offers rugged durability with a relaxed everyday fit. Crafted from premium denim fabric, it delivers comfort, breathability, and long-lasting wear. Ideal for casual outings, travel, and layering, this shirt pairs perfectly with jeans or chinos for a timeless denim-on-denim style.",
  },
  {
    _id: "10",
    name: "Cotton Polo T-Shirt",
    slug: "cotton-polo-tshirt",
    brand: "Puma",
    price: 1799,
    category: "T-Shirts",
    dressType: "Casual",
    images: ["/Main-Product-Card/10.jpg"],
    createdAt: "2025-09-21T11:15:00.000Z",
    isFav: true,
    sold: 760,
    viewCount: 3900,
    rating: 4.6,
    description:
      "Puma’s cotton polo T-shirt blends sporty elegance with everyday comfort. Made from soft breathable cotton, it ensures a relaxed feel throughout the day. Its classic collar design makes it suitable for casual outings, office wear, and weekend styling.",
  },
  {
    _id: "11",
    name: "Slim Fit Chinos",
    slug: "slim-fit-chinos",
    brand: "Allen Solly",
    price: 2899,
    category: "Pants",
    dressType: "Formal",
    images: ["/Main-Product-Card/11.jpg"],
    createdAt: "2025-09-20T14:30:00.000Z",
    isFav: false,
    sold: 520,
    viewCount: 2400,
    rating: 4.5,
    description:
      "Allen Solly slim fit chinos are designed for a polished and professional appearance. Made from premium cotton fabric, they provide excellent comfort and durability. Suitable for office wear, meetings, and semi-formal occasions.",
  },
  {
    _id: "12",
    name: "Hooded Sweatshirt",
    slug: "hooded-sweatshirt",
    brand: "Adidas",
    price: 3299,
    category: "Hoodies",
    dressType: "Casual",
    images: ["/Main-Product-Card/12.webp"],
    createdAt: "2025-09-19T10:45:00.000Z",
    isFav: true,
    sold: 890,
    viewCount: 4700,
    rating: 4.7,
    description:
      "This Adidas hooded sweatshirt offers warmth, comfort, and modern athletic styling. Crafted from soft fleece fabric, it is perfect for workouts, travel, and casual everyday wear.",
  },
  {
    _id: "14",
    name: "Classic Black Trousers",
    slug: "classic-black-trousers",
    brand: "Van Heusen",
    price: 3199,
    category: "Pants",
    dressType: "Formal",
    images: ["/Main-Product-Card/14.jpg"],
    createdAt: "2025-09-17T09:40:00.000Z",
    isFav: true,
    sold: 640,
    viewCount: 2800,
    rating: 4.6,
    description:
      "Van Heusen black trousers are tailored for a crisp and professional look. Made from premium fabric, they ensure comfort during long office hours and formal events.",
  },
  {
    _id: "15",
    name: "Canvas Casual Sneakers",
    slug: "canvas-casual-sneakers",
    brand: "Converse",
    price: 3999,
    category: "Shoes",
    dressType: "Casual",
    images: ["/Main-Product-Card/15.jpg"],
    createdAt: "2025-09-16T12:20:00.000Z",
    isFav: false,
    sold: 980,
    viewCount: 5100,
    rating: 4.8,
    description:
      "Converse canvas sneakers deliver timeless street style with unmatched comfort. Lightweight design and durable sole make them ideal for daily wear and casual outings.",
  },
  {
    _id: "16",
    name: "Checked Casual Shirt",
    slug: "checked-casual-shirt",
    brand: "Roadster",
    price: 1899,
    category: "Shirts",
    dressType: "Casual",
    images: ["/Main-Product-Card/16.jpg"],
    createdAt: "2025-09-15T10:00:00.000Z",
    isFav: false,
    sold: 560,
    viewCount: 2100,
    rating: 4.3,
    description:
      "Roadster checked casual shirt delivers a rugged yet modern look ideal for everyday wear. Made from breathable cotton fabric, it ensures comfort and durability throughout the day. Perfect for casual outings and weekend styling.",
  },
  {
    _id: "17",
    name: "Printed Summer T-Shirt",
    slug: "printed-summer-tshirt",
    brand: "H&M",
    price: 1299,
    category: "T-Shirts",
    dressType: "Casual",
    images: ["/Main-Product-Card/17.jpg"],
    createdAt: "2025-09-14T11:20:00.000Z",
    isFav: true,
    sold: 880,
    viewCount: 4600,
    rating: 4.6,
    description:
      "This printed summer T-shirt from H&M offers lightweight comfort and vibrant style. Soft cotton fabric keeps you cool while the trendy print enhances everyday casual outfits.",
  },
  {
    _id: "18",
    name: "Relaxed Fit Joggers",
    slug: "relaxed-fit-joggers",
    brand: "HRX",
    price: 2199,
    category: "Joggers",
    dressType: "Sportswear",
    images: ["/Main-Product-Card/18.jpg"],
    createdAt: "2025-09-13T08:45:00.000Z",
    isFav: false,
    sold: 740,
    viewCount: 3300,
    rating: 4.5,
    description:
      "HRX relaxed fit joggers are designed for maximum comfort and flexibility. Ideal for workouts, travel, or lounging, they offer breathable fabric and a modern athletic fit.",
  },
  {
    _id: "19",
    name: "Office Wear Pencil Skirt",
    slug: "office-wear-pencil-skirt",
    brand: "Marks & Spencer",
    price: 2999,
    category: "Skirts",
    dressType: "Formal",
    images: ["/Main-Product-Card/19.jpg"],
    createdAt: "2025-09-12T14:10:00.000Z",
    isFav: true,
    sold: 310,
    viewCount: 1700,
    rating: 4.4,
    description:
      "Marks & Spencer pencil skirt is tailored for professional elegance. Crafted from premium fabric, it offers a flattering fit suitable for office wear and formal meetings.",
  },
  {
    _id: "20",
    name: "Lightweight Windcheater Jacket",
    slug: "lightweight-windcheater-jacket",
    brand: "Decathlon",
    price: 3499,
    category: "Jackets",
    dressType: "Sportswear",
    images: ["/Main-Product-Card/20.jpg"],
    createdAt: "2025-09-11T09:30:00.000Z",
    isFav: false,
    sold: 450,
    viewCount: 2500,
    rating: 4.5,
    description:
      "Decathlon windcheater jacket provides protection against wind while remaining lightweight and breathable. Ideal for outdoor activities, travel, and daily use.",
  },
  {
    _id: "21",
    name: "Ankle Length Socks Pack",
    slug: "ankle-length-socks-pack",
    brand: "Puma",
    price: 699,
    category: "Accessories",
    dressType: "Casual",
    images: ["/Main-Product-Card/21.jpg"],
    createdAt: "2025-09-10T07:50:00.000Z",
    isFav: false,
    sold: 1200,
    viewCount: 5200,
    rating: 4.7,
    description:
      "Puma ankle length socks offer superior comfort and durability for daily wear. Made from breathable material, they provide all-day freshness and support.",
  },
  {
    _id: "22",
    name: "Formal White Cotton Shirt",
    slug: "formal-white-cotton-shirt",
    brand: "Louis Philippe",
    price: 2699,
    category: "Shirts",
    dressType: "Formal",
    images: ["/Main-Product-Card/22.jpg"],
    createdAt: "2025-09-09T10:40:00.000Z",
    isFav: true,
    sold: 670,
    viewCount: 2900,
    rating: 4.6,
    description:
      "Louis Philippe formal white cotton shirt is crafted for a refined professional look. Soft fabric and tailored fit make it ideal for office and formal occasions.",
  },
  {
    _id: "23",
    name: "Casual Slip-On Loafers",
    slug: "casual-slip-on-loafers",
    brand: "Bata",
    price: 2599,
    category: "Shoes",
    dressType: "Casual",
    images: ["/Main-Product-Card/23.jpg"],
    createdAt: "2025-09-08T16:15:00.000Z",
    isFav: false,
    sold: 540,
    viewCount: 2300,
    rating: 4.3,
    description:
      "Bata slip-on loafers combine everyday comfort with a classic casual design. Lightweight construction and cushioned soles ensure easy all-day wear.",
  },
  {
    _id: "24",
    name: "Ethnic Printed Kurta",
    slug: "ethnic-printed-kurta",
    brand: "Manyavar",
    price: 3299,
    category: "Ethnic Wear",
    dressType: "Festive",
    images: ["/Main-Product-Card/24.jpg"],
    createdAt: "2025-09-07T13:00:00.000Z",
    isFav: true,
    sold: 480,
    viewCount: 2600,
    rating: 4.6,
    description:
      "Manyavar ethnic printed kurta showcases traditional craftsmanship with a modern touch. Comfortable fabric and elegant prints make it ideal for festive occasions.",
  },
  {
    _id: "25",
    name: "High Waist Denim Shorts",
    slug: "high-waist-denim-shorts",
    brand: "Forever 21",
    price: 1799,
    category: "Shorts",
    dressType: "Casual",
    images: ["/Main-Product-Card/25.jpg"],
    createdAt: "2025-09-06T11:35:00.000Z",
    isFav: false,
    sold: 620,
    viewCount: 3100,
    rating: 4.4,
    description:
      "Forever 21 high waist denim shorts deliver trendy summer style with a flattering fit. Durable denim fabric ensures comfort and long-lasting wear.",
  },
  {
    _id: "26",
    name: "Round Neck Cotton Vest",
    slug: "round-neck-cotton-vest",
    brand: "Jockey",
    price: 599,
    category: "Innerwear",
    dressType: "Casual",
    images: ["/Main-Product-Card/26.jpg"],
    createdAt: "2025-09-05T08:25:00.000Z",
    isFav: false,
    sold: 980,
    viewCount: 4100,
    rating: 4.5,
    description:
      "Jockey round neck cotton vest offers unmatched comfort and breathability. Ideal for daily wear, it ensures softness and long-lasting durability.",
  },
  {
    _id: "27",
    name: "Classic Analog Wrist Watch",
    slug: "classic-analog-wrist-watch",
    brand: "Titan",
    price: 5499,
    category: "Accessories",
    dressType: "Formal",
    images: ["/Main-Product-Card/27.jpeg"],
    createdAt: "2025-09-04T17:10:00.000Z",
    isFav: true,
    sold: 390,
    viewCount: 2200,
    rating: 4.6,
    description:
      "Titan classic analog wrist watch combines elegance with precision craftsmanship. Designed for formal and everyday wear, it enhances sophisticated style.",
  },
  {
    _id: "28",
    name: "Sports Training Shorts",
    slug: "sports-training-shorts",
    brand: "Nike",
    price: 1899,
    category: "Shorts",
    dressType: "Sportswear",
    images: ["/Main-Product-Card/28.webp"],
    createdAt: "2025-09-03T09:50:00.000Z",
    isFav: false,
    sold: 860,
    viewCount: 4400,
    rating: 4.7,
    description:
      "Nike sports training shorts are built for performance and flexibility. Lightweight fabric and moisture-wicking technology support intense workouts.",
  },
  {
    _id: "29",
    name: "Casual Canvas Backpack",
    slug: "casual-canvas-backpack",
    brand: "Wildcraft",
    price: 2799,
    category: "Bags",
    dressType: "Casual",
    images: ["/Main-Product-Card/29.jpg"],
    createdAt: "2025-09-02T12:40:00.000Z",
    isFav: false,
    sold: 510,
    viewCount: 2600,
    rating: 4.4,
    description:
      "Wildcraft canvas backpack offers durability and spacious storage for daily use. Ideal for travel, college, and casual outings.",
  },
  {
    _id: "30",
    name: "Striped Casual Polo",
    slug: "striped-casual-polo",
    brand: "U.S. Polo Assn.",
    price: 1999,
    category: "T-Shirts",
    dressType: "Casual",
    images: ["/Main-Product-Card/30.jpg"],
    createdAt: "2025-09-01T10:10:00.000Z",
    isFav: true,
    sold: 690,
    viewCount: 3200,
    rating: 4.5,
    description:
      "U.S. Polo Assn. striped casual polo T-shirt blends classic design with modern comfort. Ideal for everyday wear and casual outings.",
  },
  {
    _id: "31",
    name: "Leather Formal Belt",
    slug: "leather-formal-belt",
    brand: "Woodland",
    price: 1499,
    category: "Accessories",
    dressType: "Formal",
    images: ["/Main-Product-Card/31.jpg"],
    createdAt: "2025-08-31T15:00:00.000Z",
    isFav: false,
    sold: 430,
    viewCount: 2000,
    rating: 4.3,
    description:
      "Woodland leather formal belt offers premium quality and durability. Perfectly complements formal trousers and office attire.",
  },
  {
    _id: "32",
    name: "Comfort Fit Night Pajamas",
    slug: "comfort-fit-night-pajamas",
    brand: "Zivame",
    price: 1599,
    category: "Sleepwear",
    dressType: "Casual",
    images: ["/Main-Product-Card/32.jpeg"],
    createdAt: "2025-08-30T20:00:00.000Z",
    isFav: true,
    sold: 780,
    viewCount: 3500,
    rating: 4.6,
    description:
      "Zivame comfort fit night pajamas provide soft fabric and relaxed design for restful sleep. Ideal for everyday nightwear.",
  },
  {
    _id: "33",
    name: "Classic Aviator Sunglasses",
    slug: "classic-aviator-sunglasses",
    brand: "Ray-Ban",
    price: 6999,
    category: "Accessories",
    dressType: "Casual",
    images: ["/Main-Product-Card/33.jpg"],
    createdAt: "2025-08-29T11:45:00.000Z",
    isFav: false,
    sold: 260,
    viewCount: 1800,
    rating: 4.7,
    description:
      "Ray-Ban classic aviator sunglasses provide iconic style with superior UV protection. Ideal for everyday outdoor use.",
  },
  {
    _id: "34",
    name: "Lightweight Cotton Scarf",
    slug: "lightweight-cotton-scarf",
    brand: "Fabindia",
    price: 1299,
    category: "Accessories",
    dressType: "Casual",
    images: ["/Main-Product-Card/34.jpeg"],
    createdAt: "2025-08-28T14:00:00.000Z",
    isFav: false,
    sold: 350,
    viewCount: 1900,
    rating: 4.4,
    description:
      "Fabindia cotton scarf offers breathable comfort with traditional patterns. Perfect for casual and ethnic styling.",
  },
  {
    _id: "35",
    name: "Formal Leather Shoes",
    slug: "formal-leather-shoes",
    brand: "Clarks",
    price: 5999,
    category: "Shoes",
    dressType: "Formal",
    images: ["/Main-Product-Card/35.jpg"],
    createdAt: "2025-08-27T09:30:00.000Z",
    isFav: true,
    sold: 480,
    viewCount: 2600,
    rating: 4.6,
    description:
      "Clarks formal leather shoes combine elegance with lasting comfort. Ideal for office wear and formal occasions.",
  },
  {
    _id: "36",
    name: "Casual Linen Shirt",
    slug: "casual-linen-shirt",
    brand: "Marks & Spencer",
    price: 2499,
    category: "Shirts",
    dressType: "Casual",
    images: ["/Main-Product-Card/36.jpeg"],
    createdAt: "2025-08-26T10:20:00.000Z",
    isFav: false,
    sold: 520,
    viewCount: 2300,
    rating: 4.4,
    description:
      "Marks & Spencer casual linen shirt offers breathable comfort and effortless summer style. Ideal for warm-weather outings.",
  },
  {
    _id: "37",
    name: "Sports Compression Tights",
    slug: "sports-compression-tights",
    brand: "Under Armour",
    price: 2999,
    category: "Activewear",
    dressType: "Sportswear",
    images: ["/Main-Product-Card/37.jpg"],
    createdAt: "2025-08-25T07:45:00.000Z",
    isFav: false,
    sold: 640,
    viewCount: 3100,
    rating: 4.6,
    description:
      "Under Armour compression tights enhance muscle support and performance during intense workouts. Designed for active lifestyles.",
  },
  {
    _id: "38",
    name: "Casual Flip Flops",
    slug: "casual-flip-flops",
    brand: "Sparx",
    price: 899,
    category: "Footwear",
    dressType: "Casual",
    images: ["/Main-Product-Card/38.jpg"],
    createdAt: "2025-08-24T16:10:00.000Z",
    isFav: false,
    sold: 920,
    viewCount: 4100,
    rating: 4.2,
    description:
      "Sparx casual flip flops offer lightweight comfort and easy everyday wear. Ideal for home, travel, and casual outings.",
  },
  {
    _id: "39",
    name: "Printed Rayon Kurti",
    slug: "printed-rayon-kurti",
    brand: "Biba",
    price: 2399,
    category: "Ethnic Wear",
    dressType: "Casual",
    images: ["/Main-Product-Card/39.jpg"],
    createdAt: "2025-08-23T13:50:00.000Z",
    isFav: true,
    sold: 560,
    viewCount: 2700,
    rating: 4.5,
    description:
      "Biba printed rayon kurti features vibrant patterns and a comfortable fit. Ideal for daily ethnic wear and casual occasions.",
  },
  {
    _id: "40",
    name: "Slim Fit Denim Jacket",
    slug: "slim-fit-denim-jacket",
    brand: "Levi's",
    price: 6499,
    category: "Jackets",
    dressType: "Casual",
    images: ["/Main-Product-Card/40.jpg"],
    createdAt: "2025-08-22T18:30:00.000Z",
    isFav: true,
    sold: 410,
    viewCount: 2400,
    rating: 4.6,
    description:
      "Levi’s slim fit denim jacket offers iconic styling with modern comfort. Perfect for layering and everyday casual looks.",
  },
  {
    _id: "41",
    name: "Basic Crew Neck Sweatshirt",
    slug: "basic-crew-neck-sweatshirt",
    brand: "Uniqlo",
    price: 2299,
    category: "Sweatshirts",
    dressType: "Casual",
    images: ["/Main-Product-Card/41.jpg"],
    createdAt: "2025-08-21T10:00:00.000Z",
    isFav: false,
    sold: 710,
    viewCount: 3400,
    rating: 4.5,
    description:
      "Uniqlo crew neck sweatshirt provides warmth and minimalist style. Ideal for layering during cooler days.",
  },
  {
    _id: "42",
    name: "Formal Grey Waistcoat",
    slug: "formal-grey-waistcoat",
    brand: "Blackberrys",
    price: 4499,
    category: "Suits",
    dressType: "Formal",
    images: ["/Main-Product-Card/42.jpg"],
    createdAt: "2025-08-20T14:40:00.000Z",
    isFav: false,
    sold: 280,
    viewCount: 1600,
    rating: 4.4,
    description:
      "Blackberrys formal grey waistcoat adds elegance and structure to formal outfits. Ideal for weddings and office events.",
  },
  {
    _id: "43",
    name: "Casual Printed Shorts",
    slug: "casual-printed-shorts",
    brand: "Superdry",
    price: 1999,
    category: "Shorts",
    dressType: "Casual",
    images: ["/Main-Product-Card/43.jpg"],
    createdAt: "2025-08-19T11:15:00.000Z",
    isFav: false,
    sold: 540,
    viewCount: 2600,
    rating: 4.3,
    description:
      "Superdry casual printed shorts offer bold style and relaxed comfort. Perfect for summer outings and casual wear.",
  },
  {
    _id: "44",
    name: "Running Track Pants",
    slug: "running-track-pants",
    brand: "Reebok",
    price: 2499,
    category: "Track Pants",
    dressType: "Sportswear",
    images: ["/Main-Product-Card/44.jpg"],
    createdAt: "2025-08-18T07:30:00.000Z",
    isFav: true,
    sold: 830,
    viewCount: 3900,
    rating: 4.6,
    description:
      "Reebok running track pants provide flexibility, breathability, and comfort for workouts and casual wear.",
  },
  {
    _id: "45",
    name: "Casual Leather Wallet",
    slug: "casual-leather-wallet",
    brand: "Fastrack",
    price: 1799,
    category: "Accessories",
    dressType: "Casual",
    images: ["/Main-Product-Card/45.jpg"],
    createdAt: "2025-08-17T16:45:00.000Z",
    isFav: false,
    sold: 690,
    viewCount: 3100,
    rating: 4.4,
    description:
      "Fastrack casual leather wallet features compact design with premium finish. Ideal for everyday use and gifting.",
  },

];


export const CART: CartType = {
  // items: [],
  items: [
    {
      product: {
        _id: "68641dc25b4c4aae182f8e1b",
        name: "Relaxed Pants",
        slug: "relaxed-pants",
        category: "outerwear",
        price: 9234.95,
        image: "https://picsum.photos/seed/yvcIOu/640/480?grayscale&blur=6",
        description: "Comfortable and stylish relaxed pants perfect for casual wear.",
      },
      quantity: 3,
      itemTotal: 27704.85,
    },
    {
      product: {
        _id: "68641dc25b4c4aae182f8e85",
        name: "Relaxed Shorts",
        slug: "relaxed-shorts-3",
        category: "outerwear",
        price: 7745.69,
        image: "https://picsum.photos/seed/PWzuGPv0O/640/480?grayscale&blur=2",
        description: "Comfortable and stylish relaxed pants perfect for casual wear.",
      },
      quantity: 6,
      itemTotal: 46474.14,
    },
    {
      product: {
        _id: "68641dc25b4c4aae182f8f53",
        name: "Essential Skirt",
        slug: "essential-skirt-4",
        category: "sportswear",
        price: 5054.89,
        image: "https://picsum.photos/seed/nshbtMD/640/480?grayscale&blur=1",
        description: "Comfortable and stylish relaxed pants perfect for casual wear.",
      },
      quantity: 2,
      itemTotal: 10109.78,
    },
  ],
  totalPrice: 84288.77,
  totalQuantity: 11,
};


export const CATEGORY: ReadonlyArray<{ image_url: string; category_name: CategoryTypes }> = [
  {
    image_url: "/All-Category/Top-Wear/2NA22S0C3-K11@12.jpg",
    category_name: "casual",
  },
  {
    image_url: "/All-Category/Top-Wear/2NA22S0C9-C11@12.jpg",
    category_name: "formal",
  },
  {
    image_url: "/All-Category/Top-Wear/2NA22S0C9-K11@12.jpg",
    category_name: "outerwear",
  },
  {
    image_url: "/All-Category/Top-Wear/2NA22S0C9-N11@12.jpg",
    category_name: "sleepwear",
  },
  {
    image_url: "/All-Category/Top-Wear/2NA22S0CA-K11@10.jpg",
    category_name: "sportswear",
  },
  {
    image_url: "/All-Category/Top-Wear/2NA22S0CA-Q11@12.jpg",
    category_name: "workoutwear",
  },
];


export const PRODUCT_CARD_RESPONSE = {
  status: 200,
  message: "Cart fetched successfully.",
  data: {
    cart: {
      items: [
        {
          product: {
            _id: "1",
            name: "Product 1",
            slug: "product-1",
            category: "bottom-wear",
            price: 6031.51,
            image: "/Main-Product-Card/1.jpg",
          },
          quantity: 2,
          itemTotal: 12063.02,
        },
        {
          product: {
            _id: "2",
            name: "Product 2",
            slug: "product-2",
            category: "bottom-wear",
            price: 6053.8,
            image: "/Main-Product-Card/2.jpeg",
          },
          quantity: 5,
          itemTotal: 30269.0,
        },
        {
          product: {
            _id: "3",
            name: "Product 3",
            slug: "product-3",
            category: "bottom-wear",
            price: 7815.41,
            image: "/Main-Product-Card/3.jpg",
          },
          quantity: 6,
          itemTotal: 46892.46,
        },
        {
          product: {
            _id: "4",
            name: "Product 4",
            slug: "product-4",
            category: "bottom-wear",
            price: 2624.49,
            image: "/Main-Product-Card/4.jpg",
          },
          quantity: 3,
          itemTotal: 7873.47,
        },
        {
          product: {
            _id: "5",
            name: "Product 5",
            slug: "product-5",
            category: "bottom-wear",
            price: 1459.7,
            image: "/Main-Product-Card/5.webp",
          },
          quantity: 5,
          itemTotal: 7298.5,
        },
        {
          product: {
            _id: "6",
            name: "Product 6",
            slug: "product-6",
            category: "bottom-wear",
            price: 1139.4,
            image: "/Main-Product-Card/6.jpg",
          },
          quantity: 1,
          itemTotal: 1139.4,
        },
        {
          product: {
            _id: "7",
            name: "Product 7",
            slug: "product-7",
            category: "bottom-wear",
            price: 2367.38,
            image: "/Main-Product-Card/7.jpg",
          },
          quantity: 5,
          itemTotal: 11836.9,
        },
        {
          product: {
            _id: "8",
            name: "Product 8",
            slug: "product-8",
            category: "bottom-wear",
            price: 6121.77,
            image: "/Main-Product-Card/8.jpg",
          },
          quantity: 1,
          itemTotal: 6121.77,
        },
        {
          product: {
            _id: "9",
            name: "Product 9",
            slug: "product-9",
            category: "bottom-wear",
            price: 1919.88,
            image: "/Main-Product-Card/9.jpg",
          },
          quantity: 5,
          itemTotal: 9599.4,
        },
        {
          product: {
            _id: "10",
            name: "Product 10",
            slug: "product-10",
            category: "bottom-wear",
            price: 5340.12,
            image: "/Main-Product-Card/10.jpg",
          },
          quantity: 5,
          itemTotal: 26700.6,
        },
        {
          product: {
            _id: "11",
            name: "Product 11",
            slug: "product-11",
            category: "bottom-wear",
            price: 5553.82,
            image: "/Main-Product-Card/11.jpg",
          },
          quantity: 5,
          itemTotal: 27769.1,
        },
        {
          product: {
            _id: "12",
            name: "Product 12",
            slug: "product-12",
            category: "bottom-wear",
            price: 9163.66,
            image: "/Main-Product-Card/12.webp",
          },
          quantity: 3,
          itemTotal: 27490.98,
        },
        {
          product: {
            _id: "13",
            name: "Product 13",
            slug: "product-13",
            category: "bottom-wear",
            price: 6088.11,
            image: "/Main-Product-Card/13.jpg",
          },
          quantity: 2,
          itemTotal: 12176.22,
        },
        {
          product: {
            _id: "14",
            name: "Product 14",
            slug: "product-14",
            category: "bottom-wear",
            price: 815.47,
            image: "/Main-Product-Card/14.jpg",
          },
          quantity: 4,
          itemTotal: 3261.88,
        },
        {
          product: {
            _id: "15",
            name: "Product 15",
            slug: "product-15",
            category: "bottom-wear",
            price: 1491.73,
            image: "/Main-Product-Card/15.jpg",
          },
          quantity: 6,
          itemTotal: 8950.38,
        },
        {
          product: {
            _id: "16",
            name: "Product 16",
            slug: "product-16",
            category: "bottom-wear",
            price: 2874.83,
            image: "/Main-Product-Card/16.jpg",
          },
          quantity: 4,
          itemTotal: 11499.32,
        },
        {
          product: {
            _id: "17",
            name: "Product 17",
            slug: "product-17",
            category: "bottom-wear",
            price: 8374.84,
            image: "/Main-Product-Card/17.jpg",
          },
          quantity: 3,
          itemTotal: 25124.52,
        },
        {
          product: {
            _id: "18",
            name: "Product 18",
            slug: "product-18",
            category: "bottom-wear",
            price: 4553.14,
            image: "/Main-Product-Card/18.jpg",
          },
          quantity: 2,
          itemTotal: 9106.28,
        },
        {
          product: {
            _id: "19",
            name: "Product 19",
            slug: "product-19",
            category: "bottom-wear",
            price: 7419.06,
            image: "/Main-Product-Card/19.jpg",
          },
          quantity: 6,
          itemTotal: 44514.36,
        },
        {
          product: {
            _id: "20",
            name: "Product 20",
            slug: "product-20",
            category: "bottom-wear",
            price: 4894.08,
            image: "/Main-Product-Card/20.jpg",
          },
          quantity: 6,
          itemTotal: 29364.48,
        },
        {
          product: {
            _id: "21",
            name: "Product 21",
            slug: "product-21",
            category: "bottom-wear",
            price: 7591.37,
            image: "/Main-Product-Card/21.jpg",
          },
          quantity: 5,
          itemTotal: 37956.85,
        },
        {
          product: {
            _id: "22",
            name: "Product 22",
            slug: "product-22",
            category: "bottom-wear",
            price: 4600.43,
            image: "/Main-Product-Card/22.jpg",
          },
          quantity: 4,
          itemTotal: 18401.72,
        },
        {
          product: {
            _id: "23",
            name: "Product 23",
            slug: "product-23",
            category: "bottom-wear",
            price: 1808.07,
            image: "/Main-Product-Card/23.jpg",
          },
          quantity: 2,
          itemTotal: 3616.14,
        },
        {
          product: {
            _id: "24",
            name: "Product 24",
            slug: "product-24",
            category: "bottom-wear",
            price: 606.1,
            image: "/Main-Product-Card/24.jpg",
          },
          quantity: 6,
          itemTotal: 3636.6,
        },
        {
          product: {
            _id: "25",
            name: "Product 25",
            slug: "product-25",
            category: "bottom-wear",
            price: 6489.05,
            image: "/Main-Product-Card/25.jpg",
          },
          quantity: 6,
          itemTotal: 38934.3,
        },
        {
          product: {
            _id: "26",
            name: "Product 26",
            slug: "product-26",
            category: "bottom-wear",
            price: 9022.62,
            image: "/Main-Product-Card/26.jpg",
          },
          quantity: 1,
          itemTotal: 9022.62,
        },
        {
          product: {
            _id: "27",
            name: "Product 27",
            slug: "product-27",
            category: "bottom-wear",
            price: 6795.38,
            image: "/Main-Product-Card/27.jpeg",
          },
          quantity: 1,
          itemTotal: 6795.38,
        },
        {
          product: {
            _id: "28",
            name: "Product 28",
            slug: "product-28",
            category: "bottom-wear",
            price: 6448.91,
            image: "/Main-Product-Card/28.webp",
          },
          quantity: 3,
          itemTotal: 19346.73,
        },
        {
          product: {
            _id: "29",
            name: "Product 29",
            slug: "product-29",
            category: "bottom-wear",
            price: 6572.66,
            image: "/Main-Product-Card/29.jpg",
          },
          quantity: 3,
          itemTotal: 19717.98,
        },
        {
          product: {
            _id: "30",
            name: "Product 30",
            slug: "product-30",
            category: "bottom-wear",
            price: 6908.69,
            image: "/Main-Product-Card/30.jpg",
          },
          quantity: 5,
          itemTotal: 34543.45,
        },
        {
          product: {
            _id: "31",
            name: "Product 31",
            slug: "product-31",
            category: "bottom-wear",
            price: 8722.03,
            image: "/Main-Product-Card/31.jpg",
          },
          quantity: 3,
          itemTotal: 26166.09,
        },
        {
          product: {
            _id: "32",
            name: "Product 32",
            slug: "product-32",
            category: "bottom-wear",
            price: 3271.04,
            image: "/Main-Product-Card/32.jpeg",
          },
          quantity: 3,
          itemTotal: 9813.12,
        },
        {
          product: {
            _id: "33",
            name: "Product 33",
            slug: "product-33",
            category: "bottom-wear",
            price: 1278.01,
            image: "/Main-Product-Card/33.jpg",
          },
          quantity: 2,
          itemTotal: 2556.02,
        },
        {
          product: {
            _id: "34",
            name: "Product 34",
            slug: "product-34",
            category: "bottom-wear",
            price: 8324.87,
            image: "/Main-Product-Card/34.jpeg",
          },
          quantity: 2,
          itemTotal: 16649.74,
        },
        {
          product: {
            _id: "35",
            name: "Product 35",
            slug: "product-35",
            category: "bottom-wear",
            price: 6727.72,
            image: "/Main-Product-Card/35.jpg",
          },
          quantity: 2,
          itemTotal: 13455.44,
        },
        {
          product: {
            _id: "36",
            name: "Product 36",
            slug: "product-36",
            category: "bottom-wear",
            price: 1807.16,
            image: "/Main-Product-Card/36.jpeg",
          },
          quantity: 6,
          itemTotal: 10842.96,
        },
        {
          product: {
            _id: "37",
            name: "Product 37",
            slug: "product-37",
            category: "bottom-wear",
            price: 543.77,
            image: "/Main-Product-Card/37.jpg",
          },
          quantity: 4,
          itemTotal: 2175.08,
        },
        {
          product: {
            _id: "38",
            name: "Product 38",
            slug: "product-38",
            category: "bottom-wear",
            price: 5912.66,
            image: "/Main-Product-Card/38.jpg",
          },
          quantity: 5,
          itemTotal: 29563.3,
        },
        {
          product: {
            _id: "39",
            name: "Product 39",
            slug: "product-39",
            category: "bottom-wear",
            price: 675.55,
            image: "/Main-Product-Card/39.jpg",
          },
          quantity: 5,
          itemTotal: 3377.75,
        },
        {
          product: {
            _id: "40",
            name: "Product 40",
            slug: "product-40",
            category: "bottom-wear",
            price: 6791.54,
            image: "/Main-Product-Card/40.jpg",
          },
          quantity: 6,
          itemTotal: 40749.24,
        },
        {
          product: {
            _id: "41",
            name: "Product 41",
            slug: "product-41",
            category: "bottom-wear",
            price: 8636.4,
            image: "/Main-Product-Card/41.jpg",
          },
          quantity: 4,
          itemTotal: 34545.6,
        },
        {
          product: {
            _id: "42",
            name: "Product 42",
            slug: "product-42",
            category: "bottom-wear",
            price: 2160.31,
            image: "/Main-Product-Card/42.jpg",
          },
          quantity: 1,
          itemTotal: 2160.31,
        },
        {
          product: {
            _id: "43",
            name: "Product 43",
            slug: "product-43",
            category: "bottom-wear",
            price: 3841.34,
            image: "/Main-Product-Card/43.jpg",
          },
          quantity: 2,
          itemTotal: 7682.68,
        },
        {
          product: {
            _id: "44",
            name: "Product 44",
            slug: "product-44",
            category: "bottom-wear",
            price: 3492.84,
            image: "/Main-Product-Card/44.jpg",
          },
          quantity: 5,
          itemTotal: 17464.2,
        },
        {
          product: {
            _id: "45",
            name: "Product 45",
            slug: "product-45",
            category: "bottom-wear",
            price: 2672.1,
            image: "/Main-Product-Card/45.jpg",
          },
          quantity: 3,
          itemTotal: 8016.3,
        },
        {
          product: {
            _id: "46",
            name: "Product 46",
            slug: "product-46",
            category: "bottom-wear",
            price: 806.53,
            image: "/Main-Product-Card/46.jpg",
          },
          quantity: 6,
          itemTotal: 4839.18,
        },
        {
          product: {
            _id: "47",
            name: "Product 47",
            slug: "product-47",
            category: "bottom-wear",
            price: 1667.47,
            image: "/Main-Product-Card/47.jpg",
          },
          quantity: 5,
          itemTotal: 8337.35,
        },
        {
          product: {
            _id: "48",
            name: "Product 48",
            slug: "product-48",
            category: "bottom-wear",
            price: 9753.58,
            image: "/Main-Product-Card/48.jpg",
          },
          quantity: 5,
          itemTotal: 48767.9,
        },
        {
          product: {
            _id: "49",
            name: "Product 49",
            slug: "product-49",
            category: "bottom-wear",
            price: 8662.54,
            image: "/Main-Product-Card/49.jpg",
          },
          quantity: 6,
          itemTotal: 51975.24,
        },
        {
          product: {
            _id: "50",
            name: "Product 50",
            slug: "product-50",
            category: "bottom-wear",
            price: 883.71,
            image: "/Main-Product-Card/50.jpg",
          },
          quantity: 1,
          itemTotal: 883.71,
        },
      ],
      totalPrice: 891045.02,
      totalQuantity: 191,
    },
  },
};


export const PRODUCT_DETAIL: ProductDetailsType[] = [
  {
    id: "68641dc25b4c4aae182f8e04",
    name: "Essential Shorts",
    slug: "essential-shorts",
    description: "Audax comburo tristis sophismata. Sufficio atqui demoror suscipio ambulo. Attero arguo careo ulterius comitatus expedita.\n    This sleek outfit is ideal for winter wear.",
    brand: "Puma",
    price: 3973.99,
    sizes: ["M", "XXL", "L", "XS", "S", "XL", "XXXL"],
    category: "workoutwear",
    dressType: "sweater",
    images: [
      "/Details-Image/45.jpg",
      "/Details-Image/46.jpg",
      "/Details-Image/47.jpg",
      "/Details-Image/48.jpg"
    ],
    stock: 71,
    sold: 2,
    rating: 7.8,
    numReviews: 100,
    attributes: {
      stretchability: "non-stretchable",
      material: "silk",
      closure: "button",
      sleeveLength: "long",
      washCare: "dry clean only"
    },
    isActive: true,
    createdAt: new Date("2025-06-28T18:30:01.204Z"),
    updatedAt: new Date("2025-07-01T18:10:51.580Z")
  }
]













export const productSpecification = [
    { name: "Product Name", value: "Urban Wild Fox Graphic T-Shirt" },
    { name: "Brand", value: "Nike" },
    { name: "Color", value: "White" },
    { name: "Material", value: "100% Cotton" },
    { name: "Fit", value: "Regular Fit" },
    { name: "Pattern", value: "Multi-color graphic print" },
    { name: "Collar", value: "Rounded" },
    { name: "Suitable for", value: "Casual wear" },
    {
        name: "Description",
        value: "Audax comburo tristis sophismata. Sufficio atqui demoror suscipio ambulo. Attero arguo careo ulterius comitatus expedita.This sleek outfit is ideal for winter wear.",
    }
];




export const reviews = [
    {
        rating: 2,
        title: "Cool and unique design!",
        comment:
            "Really loved the fox illustration—it’s different from the usual prints. Got compliments the first day I wore it. Fits perfectly too!",
        author: "Sachit Dabhi"
    },
    {
        rating: 3,
        title: "Nice but print could be sharper",
        comment:
            "Design is cool, but I expected the colors to pop a bit more in real life. Still a decent tee for everyday use.",
        author: "Jay Moteriya"
    },
    {
        rating: 4,
        title: "Great quality fabric",
        comment:
            "The cotton feels soft and breathable. Print looks durable after a couple of washes. Wish they had more colors though.",
        author: "Maulik Koli"
    },
    {
        rating: 5,
        title: "Love the fox theme!",
        comment:
            "As an animal lover, this was an instant buy. The detailing in the design is amazing and it fits true to size.",
        author: "Kunjesh Patadiya"
    }
];